baseURL = 'https://LuuBluum.github.io'
languageCode = 'en-us'
title = 'Luu's Coding Blog'
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Brad Dragun"
  info = "C++ Developer"
  description = "Brad Dragun's Rust and C++ blog"
  keywords = "blog,developer,personal"
  colorScheme = "auto"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
